project:
  type: website
  output-dir: docs  # Recommended output directory for GitHub Pages

format: 
  revealjs:
    slide-number: true
    transition: slide
    background-transition: zoom
    logo: images/quarto.png
    css: images/custom.css
execute:
  echo: true
freeze: true
editor: visual
publish:
  gh-pages: true
